### ISSUE TITLE
[Bug]: The paint list is incomplete.

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/Mini-Forge-Issue-Tracker#13]
### Description

The paint list doesn't have all of the paints from the manufacturer. There are only maybe 20 of the overall set.

### Steps to reproduce

1. Go to the paint list.
2. See that there are only a few paints but the manufacturer has a ton more.

### Expected behavior

Add the missing paints.

### Device type

iPhone 14 Pro Max

### Operating system version

16.4.1

### What app version did this occur on?

1.2.3

**Comment by O-I-CSO** [comment]
Updated the paint list in the paint API.

**Comment by ordinaryindustries** [comment]
I was going to roll this out in the 1.3 release but there are issues with cloud syncing. It's better to keep the dataset reduced to prevent unnecessary cleanup. Once we get cloud syncing fixed we can push this. Likely 1.4.

Blocked by #21.

**Comment by ordinaryindustries** [comment]
We are going to drop the manufacturer lists and instead allow users to add their own paints. NTBF.
