### ISSUE TITLE
Add more manufacturer paint lists.

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/Mini-Forge-Issue-Tracker#17]
### Description

Add additional paint lists for other manufactures. Maybe include a drop down in the settings to allow users to choose their paint system.

**Comment by O-I-CSO** [comment]
First step would be to determine what other manufacturers we want to add. Citadel seems to be the most well known/popular and that is what we have added so far. Looks like some of the below are other popular options: 

-Vallejo
-The Army Painter
-Scale75
-Formula P3

These are just some that I found looking around. Once we lock in manufacturers we can start to get lists formulated and added.

**Comment by ordinaryindustries** [comment]
Version 1.3 removes the need for manufacturer paint lists. Closing this as NTBF.
