### ISSUE TITLE
Mini Forge CFBundleShortVersionString does not match

### ISSUE THREAD

**Issue by O-I-CSO** [ordinaryindustries/Mini-Forge-Issue-Tracker#44]
### Description

The version number auto-increments each time it is archived, however, it’s not updating the marketing version number. 

### Steps to reproduce

See email from Connect

### Expected behavior

These version should update and match

### Device type

All

### Operating system version

N/A

### What app version did this occur on?

1.4

**Comment by ordinaryindustries** [comment]
Fixed this in 1.4.1. There is a bug in agvtool where it can't locate a key in the info.plist. I was attempting to automate version bumps but honestly we should be doing it manually anyway. When we archive a new version of the app we will manually increase the version.
